export default {
  // apiBaseUrl: 'http://pushpanathan.com/services/',
  apiBaseUrl:'http://dev.tieskills.com/foodapp/services/',
  imageURL: 'http://dev.tieskills.com/foodapp',
  signin: 'user/login',
  signup: 'user/register',
  signupVerifyMobile: 'user/verifyMobile',
  signinMobile:'user/login',
  categoryList:'item/fetchCategory',
  productList:'item/fetchItemList',
  mySubscriptionList: 'order/fetchSubscriptionDtlsById',
  getItemDetail: 'item/getItemById',
  getDeviveryAddress: 'user/fetchUserAddress',
  saveSubscribeOrderDetails: 'order/saveSubscribeOrderDetails',
  pauseResumeSubscription: 'order/pauseResumeSubscription',
  deleteSubscription: 'order/deleteSubscription',
}