import {Colors,Layout} from '../../constants/';
export default {
  thanksTitle:{
    fontFamily:'Font-Medium',
    fontSize:18,
    marginBottom:10
  },
  thanksText:{
    fontFamily:'Font-Medium',
    fontSize:14,
    marginRight:Layout.indent,
    paddingRight:Layout.indent,
    color:Colors.primary,
    lineHeight:18
  },
  thanksAre:{
    marginLeft:Layout.indent,
    marginTop:Layout.indent
  },
  okayBtnArea:{
  marginTop:80,
  paddingTop:70
  },
  doneBtn:{
   
    marginLeft:Layout.indent,
    marginRight:Layout.indent,
    backgroundColor:Colors.secondary,
    borderRadius:25,
    marginBottom:10
  },
  btnTextDone:{
  fontFamily:'Font-Medium',
  fontSize:20,
  color:Colors.primary
  },
  msgTitleTxt:{
  fontFamily:'Font-Medium',
  fontSize:18
},
msgText:{
  fontFamily:'Font-Regular',
  fontSize:14,
  lineHeight:16
},
};