export default {
	LOADING: 'LOADING',
	SHOWINTRO: 'SHOWINTRO',
	LANGUAGECODE: 'LANGUAGECODE',
	SHOWMODAL: 'SHOWMODAL',
	RESETSTATE: 'RESETSTATE',

	SIGNUP : 'SIGNUP',
	SIGNIN : 'SIGNIN',
	LOGOUT : 'LOGOUT',
	FORGOTPASSWORD : 'FORGOTPASSWORD',
	MOBILENO: 'MOBILENO',
	DELIVERYADDRESS: 'DELIVERYADDRESS',
	MYSUBSCRIPTION: 'MYSUBSCRIPTION',
	PRODUCTDETAIL: 'PRODUCTDETAIL',
	CARTDETAIL: 'CARTDETAIL',
	TOTALITEM: 'TOTALITEM',
	TOTALAMOUNT: 'TOTALAMOUNT',
};