
import {Colors,Layout} from '../../constants/';
export default {
textTitle:{
fontFamily:'Font-Medium',
fontSize:18,
paddingBottom:0,
lineHeight:22
},
SuccessText:{
fontFamily:'Font-Regular',
textAlign:'center',
marginLeft:Layout.indent,
marginRight:Layout.indent,
paddingLeft:Layout.indent,
paddingRight:Layout.indent,
lineHeight:20,
fontSize:14
}, 
SuccesTittle:{
fontFamily:'Font-Medium',
textAlign:'center',
fontSize:18
},
listIcons:{
borderBottomWidth:1,
borderColor:Colors.primary,
height:73,
marginLeft:Layout.indent-5,
marginRight:Layout.indent
},
addmoney:{
paddingTop:10,
paddingBottom:15
},
succesImg:{
alignItems:'center',
flex:1,
alignSelf:'center',
margin:10,
//backgroundColor:'#ddd',
width:130,
height:130,
resizeMode:'contain'
},
IconImg:{
marginLeft:0,
width:60,
height:60,
resizeMode:'contain'
},
checkOutBtn:{
backgroundColor:Colors.secondary,
borderRadius:25,
paddingVertical:10,
marginBottom:10,
height:35,
width:220,
alignSelf:'center'

},
checkOutBtnArea:{
marginLeft:Layout.indent+10,
marginRight:Layout.indent+10,
marginTop:10

},
thankText:{
fontFamily:'Font-Medium',
lineHeight:20,
fontSize:16
},
thanksHeading:{
marginTop:10,
marginBottom:10,
marginLeft:Layout.indent,
marginRight:Layout.indent,
},
infoText:{
fontSize:14,
color:Colors.gray,
fontFamily:'Font-Regular'
},
thanksInfo:{
marginLeft:Layout.indent,
marginRight:Layout.indent,
},

checkOutText:{
	color:Colors.primary,
paddingTop:5,
fontFamily:'Font-Medium',
fontSize:15,
lineHeight:18,
textTransform:'capitalize'
},
IconText:{
fontFamily:'Font-Regular',
fontSize:12,
lineHeight:13,
marginRight:0
},
IconTitle:{
marginRight:0,
fontFamily:'Font-Medium',
fontSize:14
}

       
}  